### ISSUE TITLE
Line 142 of rb_tree.py seems incorrect

### ISSUE THREAD

**Issue by lazibayer** [Enether/Red-Black-Tree#1]
I tested the code and it gave me wrong floor values instead of None when the floor values did not exist. I flipped the < sign in Line 142 and it passed my tests.

last_found_val = None if self.root.value > value else self.root.value

**Comment by stanislavkozlovski** [comment]
Yes, you seem to be absolutely correct. 
What we're trying to do there is save the root value if it can happen to be the actual floor of the input value and my check is incorrect.

Since you found this issue, it's only fair you write the pull request to fix it. If you could also add a sample unit test to make sure it works - that'd be great.

Thanks for providing interest in the project and good job!

**Comment by stanislavkozlovski** [comment]
Fixed by #2 - cb3cefb
